using System;
using System.IO;
using System.Reflection;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OpenApi.Models;
using RetrospectiveDataApi.Repositories;
using RetrospectiveDataApi.Repositories.Interfaces;
using NLog.Web;
using NLog.LayoutRenderers;
using Microsoft.Extensions.Logging;
using NLog.Extensions.Logging;
using System.Text.Json.Serialization;

namespace RetrospectiveDataApi
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers()
                            .AddJsonOptions(x =>
                            {
                                x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
                            });

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "Retrospectives API", Version = "v1" });
            });

            //This line adds Swagger generation services to our container.
            services.AddSwaggerGen(c =>
            {
                //Locate the XML file being generated by ASP.NET...
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                //... and tell Swagger to use those XML comments.
                c.IncludeXmlComments(xmlPath);
            });

            //Add depenency injection below
            services.AddScoped<IRetrospectiveDataRepository, RetrospectiveDataRepository>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Retrospectives API V1");
            });

            //map basedir from NLog.config file to root path of application folder
            LayoutRenderer.Register("basedir", (logEvent) => env.ContentRootPath);
        }
    }
}
